# Generated by Django 6.1 on 2026-09-02 04:47

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('marketplaces', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal_origem', models.CharField(choices=[('mercadolivre', 'Mercado Livre'), ('shopee', 'Shopee'), ('magalu', 'Magazine Luiza'), ('amazon', 'Amazon')], default='mercadolivre', max_length=30, verbose_name='Canal de Origem')),
                ('pedido_id_externo', models.CharField(db_index=True, max_length=100, verbose_name='ID do Pedido no Canal')),
                ('status_externo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Status no Marketplace')),
                ('status', models.CharField(choices=[('PAGO', 'Pago / Aprovado'), ('CANCELADO', 'Cancelado'), ('ENVIADO', 'Enviado / Em Trânsito'), ('ENTREGUE', 'Entregue')], default='PAGO', max_length=20, verbose_name='Status no Hub')),
                ('comprador_nome', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome do Comprador')),
                ('comprador_documento', models.CharField(blank=True, max_length=30, null=True, verbose_name='Documento do Comprador')),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Valor Total do Pedido (R$)')),
                ('valor_frete', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Valor do Frete (R$)')),
                ('data_criacao_externa', models.DateTimeField(blank=True, null=True, verbose_name='Data no Marketplace')),
                ('processado_com_sucesso', models.BooleanField(default=True, verbose_name='Processado com Sucesso')),
                ('teve_ruptura_estoque', models.BooleanField(default=False, verbose_name='Houve Ruptura de Estoque (RN-05)')),
                ('payload_original', models.JSONField(blank=True, default=dict, verbose_name='Payload Original do Webhook')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Recebido no Hub em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('conta_marketplace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='marketplaces.contamarketplace', verbose_name='Conta do Canal')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_venda', to='tenancy.loja', verbose_name='Loja (Tenant)')),
            ],
            options={
                'verbose_name': 'Pedido de Venda',
                'verbose_name_plural': 'Pedidos de Venda',
                'ordering': ['-criado_em'],
                'unique_together': {('loja', 'canal_origem', 'pedido_id_externo')},
            },
        ),
        migrations.CreateModel(
            name='ItemPedidoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id_externo', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Externo do Item')),
                ('titulo_anuncio', models.CharField(blank=True, max_length=200, null=True, verbose_name='Título no Marketplace')),
                ('quantidade', models.IntegerField(default=1, verbose_name='Quantidade Vendida')),
                ('preco_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Preço Unitário (R$)')),
                ('estoque_baixado', models.BooleanField(default=False, verbose_name='Estoque Baixado Automaticamente')),
                ('estoque_anterior', models.IntegerField(blank=True, null=True, verbose_name='Saldo de Estoque Anterior')),
                ('estoque_posterior', models.IntegerField(blank=True, null=True, verbose_name='Saldo de Estoque Posterior')),
                ('ruptura_estoque', models.BooleanField(default=False, verbose_name='Alerta de Ruptura (Saldo Negativo)')),
                ('anuncio_marketplace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_vendidos', to='catalogo.anunciomarketplace', verbose_name='Anúncio Vinculado')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_vendidos', to='catalogo.produto', verbose_name='Produto no Hub')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='pedidos.pedidovenda', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Item do Pedido de Venda',
                'verbose_name_plural': 'Itens dos Pedidos de Venda',
            },
        ),
    ]
