# Generated by Django 6.1 on 2026-09-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaces', '0005_webhookeventlog'),
        ('pedidos', '0001_initial'),
        ('tenancy', '0002_alter_loja_pais_alter_loja_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedidovenda',
            name='status_integracao',
            field=models.CharField(choices=[('vinculado', 'Vinculado'), ('pendente_vinculo', 'Pendente de Vínculo')], default='vinculado', max_length=30, verbose_name='Status de Integração do Item'),
        ),
        migrations.AddConstraint(
            model_name='pedidovenda',
            constraint=models.UniqueConstraint(fields=('canal_origem', 'pedido_id_externo'), name='unique_pedido_canal_id_externo'),
        ),
    ]
