# Generated by Django 6.1 on 2026-09-12 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_itempedidovenda_status_integracao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidovenda',
            name='teve_ruptura_estoque',
            field=models.BooleanField(default=False, verbose_name='Houve Ruptura de Estoque'),
        ),
    ]
