# Generated by Django 6.1 on 2026-10-03 05:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_itempedidovenda_public_id_pedidovenda_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedidovenda',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador único universal para exposição pública e rotas (mitigação de IDOR/BOLA).', unique=True, verbose_name='Identificador Público (UUID)'),
        ),
        migrations.AlterField(
            model_name='pedidovenda',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador único universal para exposição pública e rotas (mitigação de IDOR/BOLA).', unique=True, verbose_name='Identificador Público (UUID)'),
        ),
    ]
