# Generated by Django 6.1 on 2026-10-03 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegraRBAC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcionalidade', models.CharField(db_index=True, max_length=100, verbose_name='Código da Funcionalidade')),
                ('papel', models.CharField(db_index=True, max_length=20, verbose_name='Papel de Acesso')),
                ('concedido', models.BooleanField(default=False, verbose_name='Permissão Concedida')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Regra de Permissão RBAC',
                'verbose_name_plural': 'Regras de Permissão RBAC',
                'ordering': ['funcionalidade', 'papel'],
                'unique_together': {('funcionalidade', 'papel')},
            },
        ),
    ]
