# Generated by Django 6.1 on 2026-08-31 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(choices=[('CRIACAO_USUARIO', 'Criação de Usuário'), ('EDICAO_USUARIO', 'Edição de Dados Cadastrais'), ('TROCA_PAPEL', 'Alteração de Papel RBAC'), ('STATUS_USUARIO', 'Alteração de Status de Usuário'), ('RESET_SENHA', 'Redefinição de Senha por Administrador'), ('CRIACAO_LOJA', 'Provisionamento de Loja'), ('EDICAO_LOJA', 'Edição de Loja')], max_length=30, verbose_name='Evento')),
                ('detalhes', models.TextField(verbose_name='Detalhes da Ação / Histórico de Alterações')),
                ('ip_origem', models.CharField(blank=True, max_length=45, null=True, verbose_name='IP de Origem')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data / Hora do Evento')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Autor da Ação')),
                ('loja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_auditoria', to='core.loja', verbose_name='Loja (Tenant)')),
                ('usuario_afetado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_recebidos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Afetado')),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-criado_em'],
            },
        ),
    ]
