# Generated by Django 6.1 on 2026-08-31 04:53

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_logauditoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='logauditoria',
            name='evento',
            field=models.CharField(choices=[('CRIACAO_USUARIO', 'Criação de Usuário'), ('EDICAO_USUARIO', 'Edição de Dados Cadastrais'), ('TROCA_PAPEL', 'Alteração de Papel RBAC'), ('STATUS_USUARIO', 'Alteração de Status de Usuário'), ('RESET_SENHA', 'Redefinição de Senha por Administrador'), ('CRIACAO_LOJA', 'Provisionamento de Loja'), ('EDICAO_LOJA', 'Edição de Loja'), ('CRIACAO_PRODUTO', 'Cadastro de Produto'), ('EDICAO_PRODUTO', 'Edição de Produto'), ('EXCLUSAO_PRODUTO', 'Exclusão de Produto'), ('ALTERACAO_PRECO', 'Alteração de Preço de Venda'), ('AJUSTE_ESTOQUE', 'Ajuste Geral de Estoque'), ('BAIXA_AVARIA_ESTOQUE', 'Baixa Pontual de Estoque por Avaria'), ('CRIACAO_CATEGORIA', 'Cadastro de Categoria'), ('EDICAO_CATEGORIA', 'Edição de Categoria'), ('EXCLUSAO_CATEGORIA', 'Exclusão de Categoria')], max_length=30, verbose_name='Evento'),
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Categoria')),
                ('slug', models.SlugField(max_length=120, verbose_name='Identificador (Slug)')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição da Categoria')),
                ('ativo', models.BooleanField(default=True, verbose_name='Categoria Ativa')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='core.loja', verbose_name='Loja (Tenant)')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
                'unique_together': {('loja', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=60, verbose_name='Código SKU (Identificador Único na Loja)')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Produto')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição Detalhada do Produto')),
                ('preco', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Preço de Venda (R$)')),
                ('estoque', models.IntegerField(default=0, verbose_name='Saldo de Estoque Físico')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo (Disponível para venda)'), ('INATIVO', 'Inativo (Pausado)'), ('RASCUNHO', 'Rascunho (Em elaboração)')], default='ATIVO', max_length=20, verbose_name='Status do Produto')),
                ('meli_item_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID do Anúncio Mercado Livre (MLB...)')),
                ('status_sincronizacao', models.CharField(choices=[('NAO_SINCRONIZADO', 'Não Sincronizado'), ('PENDENTE', 'Sincronização Pendente'), ('SINCRONIZADO', 'Sincronizado com Sucesso'), ('ERRO', 'Erro de Sincronização')], default='NAO_SINCRONIZADO', max_length=20, verbose_name='Status de Sincronização')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='core.categoria', verbose_name='Categoria')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='core.loja', verbose_name='Loja (Tenant)')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome'],
                'unique_together': {('loja', 'sku')},
            },
        ),
        migrations.CreateModel(
            name='HistoricoPreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_anterior', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Anterior (R$)')),
                ('preco_novo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Novo Preço (R$)')),
                ('motivo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Motivo da Alteração')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data / Hora da Alteração')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_precos', to='core.loja', verbose_name='Loja (Tenant)')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='precos_alterados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_precos', to='core.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Histórico de Preço',
                'verbose_name_plural': 'Históricos de Preços',
                'ordering': ['-criado_em'],
            },
        ),
    ]
