# Generated by Django 6.1 on 2026-08-31 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_logauditoria_evento_categoria_produto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logauditoria',
            name='evento',
            field=models.CharField(choices=[('CRIACAO_USUARIO', 'Criação de Usuário'), ('EDICAO_USUARIO', 'Edição de Dados Cadastrais'), ('TROCA_PAPEL', 'Alteração de Papel RBAC'), ('STATUS_USUARIO', 'Alteração de Status de Usuário'), ('RESET_SENHA', 'Redefinição de Senha por Administrador'), ('CRIACAO_LOJA', 'Provisionamento de Loja'), ('EDICAO_LOJA', 'Edição de Loja'), ('CRIACAO_PRODUTO', 'Cadastro de Produto'), ('EDICAO_PRODUTO', 'Edição de Produto'), ('EXCLUSAO_PRODUTO', 'Exclusão de Produto'), ('ALTERACAO_PRECO', 'Alteração de Preço de Venda'), ('AJUSTE_ESTOQUE', 'Ajuste Geral de Estoque'), ('BAIXA_AVARIA_ESTOQUE', 'Baixa Pontual de Estoque por Avaria'), ('CRIACAO_CATEGORIA', 'Cadastro de Categoria'), ('EDICAO_CATEGORIA', 'Edição de Categoria'), ('EXCLUSAO_CATEGORIA', 'Exclusão de Categoria'), ('SYNC_PRECO_MELI', 'Sincronização de Preço (Mercado Livre)'), ('SYNC_PRECO_LOTE_MELI', 'Sincronização em Lote de Preços (Mercado Livre)'), ('REFRESH_TOKEN_MELI', 'Renovação de Token OAuth (Mercado Livre)'), ('CONFIG_CREDENCIAIS_MELI', 'Configuração de Credenciais de Integração'), ('TESTE_CONEXAO_MELI', 'Teste de Conexão com Mercado Livre')], max_length=30, verbose_name='Evento'),
        ),
        migrations.CreateModel(
            name='LogSincronizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.CharField(choices=[('MERCADO_LIVRE', 'Mercado Livre'), ('SHOPEE', 'Shopee (Backlog)'), ('MAGALU', 'Magazine Luiza (Backlog)')], default='MERCADO_LIVRE', max_length=30, verbose_name='Marketplace')),
                ('evento', models.CharField(choices=[('CRIACAO_USUARIO', 'Criação de Usuário'), ('EDICAO_USUARIO', 'Edição de Dados Cadastrais'), ('TROCA_PAPEL', 'Alteração de Papel RBAC'), ('STATUS_USUARIO', 'Alteração de Status de Usuário'), ('RESET_SENHA', 'Redefinição de Senha por Administrador'), ('CRIACAO_LOJA', 'Provisionamento de Loja'), ('EDICAO_LOJA', 'Edição de Loja'), ('CRIACAO_PRODUTO', 'Cadastro de Produto'), ('EDICAO_PRODUTO', 'Edição de Produto'), ('EXCLUSAO_PRODUTO', 'Exclusão de Produto'), ('ALTERACAO_PRECO', 'Alteração de Preço de Venda'), ('AJUSTE_ESTOQUE', 'Ajuste Geral de Estoque'), ('BAIXA_AVARIA_ESTOQUE', 'Baixa Pontual de Estoque por Avaria'), ('CRIACAO_CATEGORIA', 'Cadastro de Categoria'), ('EDICAO_CATEGORIA', 'Edição de Categoria'), ('EXCLUSAO_CATEGORIA', 'Exclusão de Categoria'), ('SYNC_PRECO_MELI', 'Sincronização de Preço (Mercado Livre)'), ('SYNC_PRECO_LOTE_MELI', 'Sincronização em Lote de Preços (Mercado Livre)'), ('REFRESH_TOKEN_MELI', 'Renovação de Token OAuth (Mercado Livre)'), ('CONFIG_CREDENCIAIS_MELI', 'Configuração de Credenciais de Integração'), ('TESTE_CONEXAO_MELI', 'Teste de Conexão com Mercado Livre')], max_length=40, verbose_name='Tipo de Operação / Evento')),
                ('item_id_externo', models.CharField(blank=True, max_length=64, null=True, verbose_name='ID Externo no Marketplace (MLB...)')),
                ('payload_enviado', models.JSONField(blank=True, default=dict, verbose_name='Payload Enviado (JSON)')),
                ('resposta_recebida', models.JSONField(blank=True, default=dict, verbose_name='Resposta Recebida da API (JSON)')),
                ('status_http', models.IntegerField(blank=True, null=True, verbose_name='Status HTTP')),
                ('sucesso', models.BooleanField(default=False, verbose_name='Operação Bem-Sucedida')),
                ('mensagem_erro', models.TextField(blank=True, null=True, verbose_name='Mensagem de Erro / Diagnóstico')),
                ('tempo_resposta_ms', models.IntegerField(blank=True, null=True, verbose_name='Tempo de Resposta (ms)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data / Hora do Disparo')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_sincronizacao', to='core.loja', verbose_name='Loja (Tenant)')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_sincronizacao', to='core.produto', verbose_name='Produto Relacionado')),
            ],
            options={
                'verbose_name': 'Log de Sincronização',
                'verbose_name_plural': 'Logs de Sincronização',
                'ordering': ['-criado_em'],
            },
        ),
    ]
