# Generated by Django 6.1 on 2026-08-31 05:58

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_logauditoria_evento_logsincronizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logauditoria',
            name='evento',
            field=models.CharField(choices=[('CRIACAO_USUARIO', 'Criação de Usuário'), ('EDICAO_USUARIO', 'Edição de Dados Cadastrais'), ('TROCA_PAPEL', 'Alteração de Papel RBAC'), ('STATUS_USUARIO', 'Alteração de Status de Usuário'), ('RESET_SENHA', 'Redefinição de Senha por Administrador'), ('CRIACAO_LOJA', 'Provisionamento de Loja'), ('EDICAO_LOJA', 'Edição de Loja'), ('CRIACAO_PRODUTO', 'Cadastro de Produto'), ('EDICAO_PRODUTO', 'Edição de Produto'), ('EXCLUSAO_PRODUTO', 'Exclusão de Produto'), ('ALTERACAO_PRECO', 'Alteração de Preço de Venda'), ('AJUSTE_ESTOQUE', 'Ajuste Geral de Estoque'), ('BAIXA_AVARIA_ESTOQUE', 'Baixa Pontual de Estoque por Avaria'), ('CRIACAO_CATEGORIA', 'Cadastro de Categoria'), ('EDICAO_CATEGORIA', 'Edição de Categoria'), ('EXCLUSAO_CATEGORIA', 'Exclusão de Categoria'), ('SYNC_PRECO_MELI', 'Sincronização de Preço (Mercado Livre)'), ('SYNC_PRECO_LOTE_MELI', 'Sincronização em Lote de Preços (Mercado Livre)'), ('REFRESH_TOKEN_MELI', 'Renovação de Token OAuth (Mercado Livre)'), ('CONFIG_CREDENCIAIS_MELI', 'Configuração de Credenciais de Integração'), ('TESTE_CONEXAO_MELI', 'Teste de Conexão com Mercado Livre'), ('WEBHOOK_VENDA_MELI', 'Processamento de Webhook de Venda'), ('BAIXA_ESTOQUE_VENDA', 'Baixa Automática de Estoque por Venda'), ('ALERTA_ESTOQUE_NEGATIVO_VENDA', 'Alerta de Ruptura / Estoque Negativo')], max_length=30, verbose_name='Evento'),
        ),
        migrations.AlterField(
            model_name='logsincronizacao',
            name='evento',
            field=models.CharField(choices=[('CRIACAO_USUARIO', 'Criação de Usuário'), ('EDICAO_USUARIO', 'Edição de Dados Cadastrais'), ('TROCA_PAPEL', 'Alteração de Papel RBAC'), ('STATUS_USUARIO', 'Alteração de Status de Usuário'), ('RESET_SENHA', 'Redefinição de Senha por Administrador'), ('CRIACAO_LOJA', 'Provisionamento de Loja'), ('EDICAO_LOJA', 'Edição de Loja'), ('CRIACAO_PRODUTO', 'Cadastro de Produto'), ('EDICAO_PRODUTO', 'Edição de Produto'), ('EXCLUSAO_PRODUTO', 'Exclusão de Produto'), ('ALTERACAO_PRECO', 'Alteração de Preço de Venda'), ('AJUSTE_ESTOQUE', 'Ajuste Geral de Estoque'), ('BAIXA_AVARIA_ESTOQUE', 'Baixa Pontual de Estoque por Avaria'), ('CRIACAO_CATEGORIA', 'Cadastro de Categoria'), ('EDICAO_CATEGORIA', 'Edição de Categoria'), ('EXCLUSAO_CATEGORIA', 'Exclusão de Categoria'), ('SYNC_PRECO_MELI', 'Sincronização de Preço (Mercado Livre)'), ('SYNC_PRECO_LOTE_MELI', 'Sincronização em Lote de Preços (Mercado Livre)'), ('REFRESH_TOKEN_MELI', 'Renovação de Token OAuth (Mercado Livre)'), ('CONFIG_CREDENCIAIS_MELI', 'Configuração de Credenciais de Integração'), ('TESTE_CONEXAO_MELI', 'Teste de Conexão com Mercado Livre'), ('WEBHOOK_VENDA_MELI', 'Processamento de Webhook de Venda'), ('BAIXA_ESTOQUE_VENDA', 'Baixa Automática de Estoque por Venda'), ('ALERTA_ESTOQUE_NEGATIVO_VENDA', 'Alerta de Ruptura / Estoque Negativo')], max_length=40, verbose_name='Tipo de Operação / Evento'),
        ),
        migrations.CreateModel(
            name='PedidoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.CharField(choices=[('MERCADO_LIVRE', 'Mercado Livre'), ('SHOPEE', 'Shopee (Backlog)'), ('MAGALU', 'Magazine Luiza (Backlog)')], default='MERCADO_LIVRE', max_length=30, verbose_name='Marketplace de Origem')),
                ('pedido_id_externo', models.CharField(db_index=True, max_length=64, verbose_name='ID do Pedido no Marketplace')),
                ('status_externo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Status Original no Marketplace')),
                ('status', models.CharField(choices=[('PAGO', 'Pago / Confirmado'), ('CRIADO', 'Criado / Pendente de Pagamento'), ('CANCELADO', 'Cancelado'), ('ENTREGUE', 'Entregue'), ('OUTRO', 'Outro Status')], default='PAGO', max_length=30, verbose_name='Status no Hub')),
                ('comprador_nome', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome do Comprador / Apelido')),
                ('comprador_documento', models.CharField(blank=True, max_length=30, null=True, verbose_name='CPF/CNPJ do Comprador')),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Valor Total (R$)')),
                ('valor_frete', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Valor do Frete (R$)')),
                ('data_criacao_externa', models.DateTimeField(blank=True, null=True, verbose_name='Data / Hora da Venda no Marketplace')),
                ('processado_com_sucesso', models.BooleanField(default=False, verbose_name='Processado com Sucesso')),
                ('teve_ruptura_estoque', models.BooleanField(default=False, verbose_name='Teve Ruptura de Estoque (Saldo Negativo)')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações do Pedido / Diagnóstico')),
                ('payload_original', models.JSONField(blank=True, default=dict, verbose_name='Payload Original do Webhook/Pedido (JSON)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Recebido em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_venda', to='core.loja', verbose_name='Loja (Tenant)')),
            ],
            options={
                'verbose_name': 'Pedido de Venda',
                'verbose_name_plural': 'Pedidos de Venda',
                'ordering': ['-criado_em'],
                'unique_together': {('loja', 'marketplace', 'pedido_id_externo')},
            },
        ),
        migrations.CreateModel(
            name='ItemPedidoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id_externo', models.CharField(blank=True, max_length=64, null=True, verbose_name='ID do Anúncio (MLB...)')),
                ('sku_informado', models.CharField(blank=True, max_length=60, null=True, verbose_name='SKU no Pedido')),
                ('titulo_anuncio', models.CharField(max_length=255, verbose_name='Título do Anúncio')),
                ('quantidade', models.IntegerField(default=1, verbose_name='Quantidade Vendida')),
                ('preco_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Preço Unitário (R$)')),
                ('estoque_baixado', models.BooleanField(default=False, verbose_name='Estoque Foi Abatido')),
                ('estoque_anterior', models.IntegerField(blank=True, null=True, verbose_name='Estoque Anterior')),
                ('estoque_posterior', models.IntegerField(blank=True, null=True, verbose_name='Estoque Posterior')),
                ('ruptura_estoque', models.BooleanField(default=False, verbose_name='Entrou em Ruptura (Saldo Negativo)')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_vendidos', to='core.produto', verbose_name='Produto no Catálogo')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.pedidovenda', verbose_name='Pedido de Venda')),
            ],
            options={
                'verbose_name': 'Item do Pedido de Venda',
                'verbose_name_plural': 'Itens do Pedido de Venda',
            },
        ),
    ]
