# Generated by Django 6.1 on 2026-08-31 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_logauditoria_evento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='magalu_ativo',
            field=models.BooleanField(default=False, verbose_name='Integração Magalu Ativa'),
        ),
        migrations.AddField(
            model_name='loja',
            name='shopee_ativo',
            field=models.BooleanField(default=False, verbose_name='Integração Shopee Ativa'),
        ),
        migrations.AddField(
            model_name='loja',
            name='sincronizar_canal_origem_venda',
            field=models.BooleanField(default=False, help_text='Por padrão (desmarcado), assume-se que o marketplace onde a venda ocorreu já abateu o estoque em seu checkout, transmitindo o saldo apenas para os demais canais. Marque esta opção caso o marketplace não controle o estoque diretamente.', verbose_name='Disparar Broadcast Também para o Canal de Origem da Venda'),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='evento',
            field=models.CharField(choices=[('CRIACAO_USUARIO', 'Criação de Usuário'), ('EDICAO_USUARIO', 'Edição de Dados Cadastrais'), ('TROCA_PAPEL', 'Alteração de Papel RBAC'), ('STATUS_USUARIO', 'Alteração de Status de Usuário'), ('RESET_SENHA', 'Redefinição de Senha por Administrador'), ('CRIACAO_LOJA', 'Provisionamento de Loja'), ('EDICAO_LOJA', 'Edição de Loja'), ('CRIACAO_PRODUTO', 'Cadastro de Produto'), ('EDICAO_PRODUTO', 'Edição de Produto'), ('EXCLUSAO_PRODUTO', 'Exclusão de Produto'), ('ALTERACAO_PRECO', 'Alteração de Preço de Venda'), ('AJUSTE_ESTOQUE', 'Ajuste Geral de Estoque'), ('BAIXA_AVARIA_ESTOQUE', 'Baixa Pontual de Estoque por Avaria'), ('CRIACAO_CATEGORIA', 'Cadastro de Categoria'), ('EDICAO_CATEGORIA', 'Edição de Categoria'), ('EXCLUSAO_CATEGORIA', 'Exclusão de Categoria'), ('SYNC_PRECO_MELI', 'Sincronização de Preço (Mercado Livre)'), ('SYNC_PRECO_LOTE_MELI', 'Sincronização em Lote de Preços (Mercado Livre)'), ('REFRESH_TOKEN_MELI', 'Renovação de Token OAuth (Mercado Livre)'), ('CONFIG_CREDENCIAIS_MELI', 'Configuração de Credenciais de Integração'), ('TESTE_CONEXAO_MELI', 'Teste de Conexão com Mercado Livre'), ('WEBHOOK_VENDA_MELI', 'Processamento de Webhook de Venda'), ('BAIXA_ESTOQUE_VENDA', 'Baixa Automática de Estoque por Venda'), ('ALERTA_ESTOQUE_NEGATIVO_VENDA', 'Alerta de Ruptura / Estoque Negativo'), ('BROADCAST_ESTOQUE', 'Broadcast Multi-Canal de Estoque'), ('SYNC_ESTOQUE_MELI', 'Sincronização de Estoque (Mercado Livre)'), ('SYNC_ESTOQUE_SHOPEE', 'Sincronização de Estoque (Shopee)'), ('SYNC_ESTOQUE_MAGALU', 'Sincronização de Estoque (Magalu)')], max_length=30, verbose_name='Evento'),
        ),
        migrations.AlterField(
            model_name='logsincronizacao',
            name='evento',
            field=models.CharField(choices=[('CRIACAO_USUARIO', 'Criação de Usuário'), ('EDICAO_USUARIO', 'Edição de Dados Cadastrais'), ('TROCA_PAPEL', 'Alteração de Papel RBAC'), ('STATUS_USUARIO', 'Alteração de Status de Usuário'), ('RESET_SENHA', 'Redefinição de Senha por Administrador'), ('CRIACAO_LOJA', 'Provisionamento de Loja'), ('EDICAO_LOJA', 'Edição de Loja'), ('CRIACAO_PRODUTO', 'Cadastro de Produto'), ('EDICAO_PRODUTO', 'Edição de Produto'), ('EXCLUSAO_PRODUTO', 'Exclusão de Produto'), ('ALTERACAO_PRECO', 'Alteração de Preço de Venda'), ('AJUSTE_ESTOQUE', 'Ajuste Geral de Estoque'), ('BAIXA_AVARIA_ESTOQUE', 'Baixa Pontual de Estoque por Avaria'), ('CRIACAO_CATEGORIA', 'Cadastro de Categoria'), ('EDICAO_CATEGORIA', 'Edição de Categoria'), ('EXCLUSAO_CATEGORIA', 'Exclusão de Categoria'), ('SYNC_PRECO_MELI', 'Sincronização de Preço (Mercado Livre)'), ('SYNC_PRECO_LOTE_MELI', 'Sincronização em Lote de Preços (Mercado Livre)'), ('REFRESH_TOKEN_MELI', 'Renovação de Token OAuth (Mercado Livre)'), ('CONFIG_CREDENCIAIS_MELI', 'Configuração de Credenciais de Integração'), ('TESTE_CONEXAO_MELI', 'Teste de Conexão com Mercado Livre'), ('WEBHOOK_VENDA_MELI', 'Processamento de Webhook de Venda'), ('BAIXA_ESTOQUE_VENDA', 'Baixa Automática de Estoque por Venda'), ('ALERTA_ESTOQUE_NEGATIVO_VENDA', 'Alerta de Ruptura / Estoque Negativo'), ('BROADCAST_ESTOQUE', 'Broadcast Multi-Canal de Estoque'), ('SYNC_ESTOQUE_MELI', 'Sincronização de Estoque (Mercado Livre)'), ('SYNC_ESTOQUE_SHOPEE', 'Sincronização de Estoque (Shopee)'), ('SYNC_ESTOQUE_MAGALU', 'Sincronização de Estoque (Magalu)')], max_length=40, verbose_name='Tipo de Operação / Evento'),
        ),
    ]
