# Generated by Django 6.1 on 2026-08-31 12:25

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_loja_magalu_ativo_loja_shopee_ativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='custo_aquisicao',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Custo de compra ou fabricação unitária do produto.', max_digits=10, verbose_name='Custo de Aquisição / CMV (R$)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='custo_embalagem',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Custo de insumos e embalagem deste produto. Se 0, herda o padrão da loja.', max_digits=10, verbose_name='Custo Específico de Embalagem (R$)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='modalidade_full',
            field=models.BooleanField(default=False, help_text='Se marcado, o custo próprio de embalagem é zerado pois o marketplace assume o envio.', verbose_name='Modalidade Full / Fulfillment'),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='evento',
            field=models.CharField(choices=[('CRIACAO_USUARIO', 'Criação de Usuário'), ('EDICAO_USUARIO', 'Edição de Dados Cadastrais'), ('TROCA_PAPEL', 'Alteração de Papel RBAC'), ('STATUS_USUARIO', 'Alteração de Status de Usuário'), ('RESET_SENHA', 'Redefinição de Senha por Administrador'), ('CRIACAO_LOJA', 'Provisionamento de Loja'), ('EDICAO_LOJA', 'Edição de Loja'), ('CRIACAO_PRODUTO', 'Cadastro de Produto'), ('EDICAO_PRODUTO', 'Edição de Produto'), ('EXCLUSAO_PRODUTO', 'Exclusão de Produto'), ('ALTERACAO_PRECO', 'Alteração de Preço de Venda'), ('AJUSTE_ESTOQUE', 'Ajuste Geral de Estoque'), ('BAIXA_AVARIA_ESTOQUE', 'Baixa Pontual de Estoque por Avaria'), ('CRIACAO_CATEGORIA', 'Cadastro de Categoria'), ('EDICAO_CATEGORIA', 'Edição de Categoria'), ('EXCLUSAO_CATEGORIA', 'Exclusão de Categoria'), ('SYNC_PRECO_MELI', 'Sincronização de Preço (Mercado Livre)'), ('SYNC_PRECO_LOTE_MELI', 'Sincronização em Lote de Preços (Mercado Livre)'), ('REFRESH_TOKEN_MELI', 'Renovação de Token OAuth (Mercado Livre)'), ('CONFIG_CREDENCIAIS_MELI', 'Configuração de Credenciais de Integração'), ('TESTE_CONEXAO_MELI', 'Teste de Conexão com Mercado Livre'), ('WEBHOOK_VENDA_MELI', 'Processamento de Webhook de Venda'), ('BAIXA_ESTOQUE_VENDA', 'Baixa Automática de Estoque por Venda'), ('ALERTA_ESTOQUE_NEGATIVO_VENDA', 'Alerta de Ruptura / Estoque Negativo'), ('BROADCAST_ESTOQUE', 'Broadcast Multi-Canal de Estoque'), ('SYNC_ESTOQUE_MELI', 'Sincronização de Estoque (Mercado Livre)'), ('SYNC_ESTOQUE_SHOPEE', 'Sincronização de Estoque (Shopee)'), ('SYNC_ESTOQUE_MAGALU', 'Sincronização de Estoque (Magalu)'), ('SIMULACAO_FINANCEIRA_PROMO', 'Simulação de Viabilidade Promocional')], max_length=30, verbose_name='Evento'),
        ),
        migrations.AlterField(
            model_name='logsincronizacao',
            name='evento',
            field=models.CharField(choices=[('CRIACAO_USUARIO', 'Criação de Usuário'), ('EDICAO_USUARIO', 'Edição de Dados Cadastrais'), ('TROCA_PAPEL', 'Alteração de Papel RBAC'), ('STATUS_USUARIO', 'Alteração de Status de Usuário'), ('RESET_SENHA', 'Redefinição de Senha por Administrador'), ('CRIACAO_LOJA', 'Provisionamento de Loja'), ('EDICAO_LOJA', 'Edição de Loja'), ('CRIACAO_PRODUTO', 'Cadastro de Produto'), ('EDICAO_PRODUTO', 'Edição de Produto'), ('EXCLUSAO_PRODUTO', 'Exclusão de Produto'), ('ALTERACAO_PRECO', 'Alteração de Preço de Venda'), ('AJUSTE_ESTOQUE', 'Ajuste Geral de Estoque'), ('BAIXA_AVARIA_ESTOQUE', 'Baixa Pontual de Estoque por Avaria'), ('CRIACAO_CATEGORIA', 'Cadastro de Categoria'), ('EDICAO_CATEGORIA', 'Edição de Categoria'), ('EXCLUSAO_CATEGORIA', 'Exclusão de Categoria'), ('SYNC_PRECO_MELI', 'Sincronização de Preço (Mercado Livre)'), ('SYNC_PRECO_LOTE_MELI', 'Sincronização em Lote de Preços (Mercado Livre)'), ('REFRESH_TOKEN_MELI', 'Renovação de Token OAuth (Mercado Livre)'), ('CONFIG_CREDENCIAIS_MELI', 'Configuração de Credenciais de Integração'), ('TESTE_CONEXAO_MELI', 'Teste de Conexão com Mercado Livre'), ('WEBHOOK_VENDA_MELI', 'Processamento de Webhook de Venda'), ('BAIXA_ESTOQUE_VENDA', 'Baixa Automática de Estoque por Venda'), ('ALERTA_ESTOQUE_NEGATIVO_VENDA', 'Alerta de Ruptura / Estoque Negativo'), ('BROADCAST_ESTOQUE', 'Broadcast Multi-Canal de Estoque'), ('SYNC_ESTOQUE_MELI', 'Sincronização de Estoque (Mercado Livre)'), ('SYNC_ESTOQUE_SHOPEE', 'Sincronização de Estoque (Shopee)'), ('SYNC_ESTOQUE_MAGALU', 'Sincronização de Estoque (Magalu)'), ('SIMULACAO_FINANCEIRA_PROMO', 'Simulação de Viabilidade Promocional')], max_length=40, verbose_name='Tipo de Operação / Evento'),
        ),
        migrations.CreateModel(
            name='ConfiguracaoTaxasLoja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aliquota_imposto', models.DecimalField(decimal_places=2, default=Decimal('6.00'), help_text='Percentual médio de tributos (ex.: Simples Nacional / Lucro Presumido).', max_digits=5, verbose_name='Alíquota Média de Imposto (%)')),
                ('custo_embalagem_padrao', models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Custo padrão de embalagem caso o produto não possua custo customizado.', max_digits=10, verbose_name='Custo Padrão de Embalagem (R$)')),
                ('margem_minima_seguranca', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Margem de contribuição mínima recomendada para evitar risco de prejuízo operacional.', max_digits=5, verbose_name='Margem Mínima de Segurança (%)')),
                ('custos_fixos_mensais', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Custos operacionais fixos mensais da loja (aluguel, folha, energia, etc.).', max_digits=12, verbose_name='Custos Fixos Mensais (R$)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('loja', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracao_taxas', to='core.loja', verbose_name='Loja')),
            ],
            options={
                'verbose_name': 'Configuração de Taxas da Loja',
                'verbose_name_plural': 'Configurações de Taxas das Lojas',
            },
        ),
        migrations.CreateModel(
            name='ParametroCanalMarketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.CharField(choices=[('mercadolivre_classico', 'Mercado Livre (Clássico)'), ('mercadolivre_premium', 'Mercado Livre (Premium)'), ('shopee', 'Shopee'), ('magalu', 'Magazine Luiza')], max_length=50, verbose_name='Canal de Marketplace')),
                ('comissao_padrao', models.DecimalField(decimal_places=2, default=Decimal('16.00'), help_text='Comissão percentual retida pelo marketplace (ex: 16% Mercado Livre Clássico, 19% Premium).', max_digits=5, verbose_name='Comissão Padrão (%)')),
                ('frete_gratis_piso', models.DecimalField(decimal_places=2, default=Decimal('79.00'), help_text='Valor a partir do qual incide cobrança de frete no lojista (ex.: R$ 79,00).', max_digits=10, verbose_name='Piso de Frete Grátis (R$)')),
                ('taxa_frete_acima_limite', models.DecimalField(decimal_places=2, default=Decimal('18.00'), help_text='Custo médio de frete pago pelo lojista para produtos a partir do piso (ex.: R$ 18,00).', max_digits=10, verbose_name='Taxa de Frete Acima do Piso (R$)')),
                ('taxa_fixa_abaixo_limite', models.DecimalField(decimal_places=2, default=Decimal('6.00'), help_text='Tarifa fixa cobrada por unidade em itens de baixo valor (ex.: R$ 6,00).', max_digits=10, verbose_name='Taxa Fixa Abaixo do Piso (R$)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Canal Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros_canais', to='core.loja', verbose_name='Loja')),
            ],
            options={
                'verbose_name': 'Parâmetro de Canal de Marketplace',
                'verbose_name_plural': 'Parâmetros de Canais de Marketplaces',
                'unique_together': {('loja', 'marketplace')},
            },
        ),
    ]
