# Generated by Django 6.1 on 2026-08-31 12:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_produto_custo_aquisicao_produto_custo_embalagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='custo_aquisicao',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Custo de compra ou fabricação unitária do produto.', max_digits=10, verbose_name='Custo de Aquisição / CMV (R$)'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='custo_embalagem',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Custo de insumos e embalagem deste produto. Se 0, herda o padrão da loja.', max_digits=10, verbose_name='Custo Específico de Embalagem (R$)'),
        ),
    ]
