# Generated by Django 6.1 on 2026-09-02 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome da Loja')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Identificador (Slug)')),
                ('cnpj', models.CharField(max_length=20, unique=True, verbose_name='CNPJ')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=30, null=True, verbose_name='Inscrição Estadual')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail de Contato')),
                ('cep', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP')),
                ('endereco', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço / Logradouro')),
                ('numero', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, null=True, verbose_name='Estado (UF)')),
                ('pais', models.CharField(default='Brasil', max_length=50, verbose_name='País')),
                ('ativo', models.BooleanField(default=True, verbose_name='Loja Ativa')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Loja',
                'verbose_name_plural': 'Lojas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('DEV', 'Desenvolvedor (DEV) — Escopo Global'), ('ADMIN', 'Administrador da Loja (ADMIN)'), ('SUPERVISOR', 'Supervisor da Loja (SUPERVISOR)'), ('USUARIO', 'Usuário Padrão da Loja (USUÁRIO)')], default='USUARIO', max_length=20, verbose_name='Papel de Acesso')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('loja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='tenancy.loja', verbose_name='Loja (Tenant)')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
            },
        ),
        migrations.CreateModel(
            name='ModuloLoja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(choices=[('catalogo', 'Gestão de Catálogo e Produtos'), ('pedidos', 'Vendas e Pedidos Multicanal'), ('marketplaces', 'Hub de Conectores de Marketplaces'), ('financeiro', 'Motor de Inteligência Financeira')], max_length=30, verbose_name='Módulo do Sistema')),
                ('ativo', models.BooleanField(default=True, verbose_name='Módulo Ativo para a Loja')),
                ('ativado_em', models.DateTimeField(auto_now=True, verbose_name='Última Alteração de Status')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='tenancy.loja', verbose_name='Loja (Tenant)')),
            ],
            options={
                'verbose_name': 'Módulo da Loja',
                'verbose_name_plural': 'Módulos das Lojas',
                'ordering': ['loja', 'modulo'],
                'unique_together': {('loja', 'modulo')},
            },
        ),
    ]
