# Generated by Django 6.1 on 2026-09-02 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loja',
            name='pais',
            field=models.CharField(blank=True, default='Brasil', max_length=50, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='loja',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True, verbose_name='Identificador (Slug)'),
        ),
    ]
