# Generated by Django 6.1 on 2026-10-03 05:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0002_alter_loja_pais_alter_loja_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador único universal para exposição pública e rotas (mitigação de IDOR/BOLA).', null=True, verbose_name='Identificador Público (UUID)'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador único universal para exposição pública e rotas (mitigação de IDOR/BOLA).', null=True, verbose_name='Identificador Público (UUID)'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='papel',
            field=models.CharField(choices=[('DEV', 'Desenvolvedor (DEV) — Escopo Global'), ('ADMIN', 'Administrador (ADMIN)'), ('SUPERVISOR', 'Supervisor (SUPERVISOR)'), ('USUARIO', 'Usuário (USUÁRIO)')], default='USUARIO', max_length=20, verbose_name='Papel de Acesso'),
        ),
    ]
