# Generated by Django 6.1 on 2026-10-02 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0002_alter_loja_pais_alter_loja_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibilidade_publica', models.BooleanField(default=True, help_text="Se True, a rota '/' serve a Landing Page. Se False, '/' serve Login e páginas públicas respondem 404.", verbose_name='Visibilidade Pública Ativa')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('loja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='config_site', to='tenancy.loja', verbose_name='Loja (Tenant)')),
            ],
            options={
                'verbose_name': 'Configuração do Site',
                'verbose_name_plural': 'Configurações do Site',
            },
        ),
        migrations.CreateModel(
            name='ConfigTema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(choices=[('T01', 'T01 — Alegre'), ('T02', 'T02 — Sofisticado'), ('T03', 'T03 — Sóbrio'), ('T04', 'T04 — Animado'), ('T05', 'T05 — Profissional (Padrão)'), ('T06', 'T06 — Luxuoso'), ('T07', 'T07 — SoftClean'), ('T08', 'T08 — Noturno'), ('T09', 'T09 — Acessível'), ('T10', 'T10 — Outro (Personalizado)')], default='T05', max_length=5, verbose_name='Modelo de Design')),
                ('cor_fundos', models.CharField(default='#F8FAFC', max_length=7, verbose_name='Cor de Fundos')),
                ('cor_destaques', models.CharField(default='#1E3A8A', max_length=7, verbose_name='Cor de Destaques')),
                ('cor_escritas', models.CharField(default='#0F172A', max_length=7, verbose_name='Cor de Escritas')),
                ('raio', models.CharField(choices=[('reto', 'Reto (0)'), ('suave', 'Suave (.375rem)'), ('arredondado', 'Arredondado (1rem)'), ('pilula', 'Pílula (2rem)')], default='suave', max_length=15, verbose_name='Raio dos Cantos')),
                ('sombra', models.CharField(choices=[('nenhuma', 'Nenhuma (Apenas bordas)'), ('suave', 'Suave'), ('marcada', 'Marcada'), ('difusa', 'Difusa')], default='suave', max_length=15, verbose_name='Sombra das Superfícies')),
                ('densidade', models.CharField(choices=[('compacta', 'Compacta (.75)'), ('confortavel', 'Confortável (1.0)'), ('ampla', 'Ampla (1.35)')], default='confortavel', max_length=15, verbose_name='Densidade e Espaçamento')),
                ('movimento', models.CharField(choices=[('nenhum', 'Nenhum (0s)'), ('discreto', 'Discreto (.15s)'), ('expressivo', 'Expressivo (.35s)')], default='discreto', max_length=15, verbose_name='Movimento e Transições')),
                ('tipografia', models.CharField(choices=[('sans', 'Sans do Sistema'), ('arredondada', 'Arredondada'), ('serifa-titulos', 'Serifa nos Títulos')], default='sans', max_length=20, verbose_name='Pilha Tipográfica')),
                ('icones', models.CharField(choices=[('contorno', 'Contorno'), ('preenchido', 'Preenchido')], default='contorno', max_length=15, verbose_name='Estilo dos Ícones')),
                ('shell_variante', models.CharField(default='topo', max_length=30, verbose_name='Variante de Casca Autenticada')),
                ('versao', models.CharField(blank=True, max_length=64, verbose_name='Hash de Versionamento do CSS')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('loja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='config_temas', to='tenancy.loja', verbose_name='Loja (Tenant)')),
            ],
            options={
                'verbose_name': 'Configuração de Tema',
                'verbose_name_plural': 'Configurações de Tema',
            },
        ),
    ]
