# Generated by Django 6.1 on 2026-09-02 04:47

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoTaxasLoja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aliquota_imposto', models.DecimalField(decimal_places=4, default=Decimal('0.0400'), help_text='Percentual de imposto sobre faturamento bruto (Simples Nacional / ICMS).', max_digits=5, verbose_name='Alíquota de Imposto (ex: 0.04 = 4%)')),
                ('custo_embalagem_padrao', models.DecimalField(decimal_places=2, default=Decimal('2.50'), help_text='Valor padrão aplicado a produtos que não possuem custo específico de embalagem.', max_digits=10, verbose_name='Custo de Embalagem Padrão (R$)')),
                ('margem_minima_seguranca', models.DecimalField(decimal_places=4, default=Decimal('0.1500'), help_text='Piso mínimo de margem desejada pela loja para classificar uma promoção como viável.', max_digits=5, verbose_name='Margem Líquida Mínima de Segurança (ex: 0.15 = 15%)')),
                ('custos_fixos_mensais', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Soma de aluguel, salários, softwares e utilidades da loja.', max_digits=12, verbose_name='Custos Fixos Mensais da Operação (R$)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('loja', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_taxas', to='tenancy.loja', verbose_name='Loja (Tenant)')),
            ],
            options={
                'verbose_name': 'Configuração de Taxas da Loja',
                'verbose_name_plural': 'Configurações de Taxas das Lojas',
            },
        ),
        migrations.CreateModel(
            name='ParametroCanalMarketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.CharField(choices=[('mercadolivre_classico', 'Mercado Livre — Clássico (12% comissão)'), ('mercadolivre_premium', 'Mercado Livre — Premium (17% comissão)'), ('shopee', 'Shopee (14% comissão)'), ('magalu', 'Magazine Luiza (16% comissão)'), ('amazon', 'Amazon (15% comissão)')], max_length=50, verbose_name='Canal de Marketplace / Categoria de Anúncio')),
                ('comissao_padrao', models.DecimalField(decimal_places=4, default=Decimal('0.1600'), help_text='Taxa percentual cobrada pelo marketplace sobre o valor de venda.', max_digits=5, verbose_name='Comissão do Marketplace (ex: 0.16 = 16%)')),
                ('frete_gratis_piso', models.DecimalField(decimal_places=2, default=Decimal('79.00'), help_text='Acima deste valor, o frete é obrigatório e subsidiado pelo vendedor.', max_digits=10, verbose_name='Piso de Frete Grátis Obrigatório (R$)')),
                ('taxa_frete_acima_limite', models.DecimalField(decimal_places=2, default=Decimal('18.00'), help_text='Valor fixo debitado do vendedor para envios acima do piso de frete grátis.', max_digits=10, verbose_name='Custo de Frete Acima do Piso (R$)')),
                ('taxa_fixa_abaixo_limite', models.DecimalField(decimal_places=2, default=Decimal('6.00'), help_text='Taxa administrativa cobrada em vendas de baixo ticket.', max_digits=10, verbose_name='Taxa Fixa por Item Abaixo do Piso (R$)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros_canais', to='tenancy.loja', verbose_name='Loja (Tenant)')),
            ],
            options={
                'verbose_name': 'Parâmetro de Canal de Marketplace',
                'verbose_name_plural': 'Parâmetros de Canais de Marketplaces',
                'unique_together': {('loja', 'marketplace')},
            },
        ),
    ]
