# Generated by Django 6.1 on 2026-10-04 04:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaotaxasloja',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador único universal para exposição pública e rotas (mitigação de IDOR/BOLA).', null=True, verbose_name='Identificador Público (UUID)'),
        ),
        migrations.AddField(
            model_name='parametrocanalmarketplace',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador único universal para exposição pública e rotas (mitigação de IDOR/BOLA).', null=True, verbose_name='Identificador Público (UUID)'),
        ),
    ]
