# Generated by Django 6.1 on 2026-09-06 23:07

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0002_alter_anunciomarketplace_unique_together_and_more'),
        ('marketplaces', '0004_alter_contamarketplace_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id_externo', models.CharField(db_index=True, max_length=64, verbose_name='ID Externo do Anúncio (ex: MLB123456789)')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título do Anúncio')),
                ('preco_venda', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Preço de Venda (R$)')),
                ('estoque_publicado', models.IntegerField(default=0, verbose_name='Estoque Publicado no Canal (Snapshot Lógico)')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('paused', 'Pausado'), ('closed', 'Finalizado'), ('under_review', 'Em Revisão'), ('inactive', 'Inativo')], default='active', max_length=30, verbose_name='Status do Anúncio')),
                ('sku_vendedor', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='SKU Informado pelo Vendedor (seller_custom_field)')),
                ('thumbnail', models.URLField(blank=True, max_length=500, null=True, verbose_name='Imagem / Thumbnail')),
                ('permalink', models.URLField(blank=True, max_length=500, null=True, verbose_name='Link Público do Anúncio')),
                ('data_sincronizacao', models.DateTimeField(auto_now=True, verbose_name='Última Sincronização')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anuncios_publicados', to='marketplaces.contamarketplace', verbose_name='Conta do Marketplace')),
            ],
            options={
                'verbose_name': 'Anúncio',
                'verbose_name_plural': 'Anúncios',
                'ordering': ['-atualizado_em'],
                'unique_together': {('conta', 'item_id_externo')},
            },
        ),
        migrations.CreateModel(
            name='AnuncioComposicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade por Embalagem / Multiplicador do Kit')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_composicao', to='anuncios.anuncio', verbose_name='Anúncio')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anuncios_vinculados', to='catalogo.produto', verbose_name='Produto Físico no Catálogo (Fonte da Verdade)')),
            ],
            options={
                'verbose_name': 'Composição do Anúncio',
                'verbose_name_plural': 'Composições do Anúncio',
                'ordering': ['anuncio', 'produto'],
                'unique_together': {('anuncio', 'produto')},
            },
        ),
    ]
