# Generated by Django 6.1 on 2026-09-07 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0001_initial'),
        ('catalogo', '0002_alter_anunciomarketplace_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anunciocomposicao',
            name='anuncio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_composicao', related_query_name='composicoes', to='anuncios.anuncio', verbose_name='Anúncio'),
        ),
        migrations.AlterField(
            model_name='anunciocomposicao',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anuncios_vinculados', related_query_name='composicoes', to='catalogo.produto', verbose_name='Produto Físico no Catálogo (Fonte da Verdade)'),
        ),
    ]
