# Generated by Django 6.1 on 2026-09-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0002_alter_anunciocomposicao_anuncio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='status_sincronizacao',
            field=models.CharField(choices=[('SINCRONIZADO', 'Sincronizado'), ('PENDENTE', 'Pendente de Envio'), ('IGNORADO', 'Ignorado / Descartado')], db_index=True, default='SINCRONIZADO', max_length=20, verbose_name='Estado da Sincronização'),
        ),
    ]
