# Generated by Django 6.1 on 2026-09-07 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrar_status_sincronizacao(apps, schema_editor):
    Anuncio = apps.get_model('anuncios', 'Anuncio')
    for anc in Anuncio.objects.all():
        if anc.status_sincronizacao == 'SINCRONIZADO':
            anc.status_sincronizacao = 'ENVIADO'
        elif anc.status_sincronizacao == 'IGNORADO':
            anc.status_sincronizacao = 'CANCELADO'
        elif anc.status_sincronizacao == 'PENDENTE':
            anc.status_sincronizacao = 'PENDENTE'
        else:
            anc.status_sincronizacao = 'PENDENTE'
        anc.save(update_fields=['status_sincronizacao'])


def reverter_migracao_status(apps, schema_editor):
    Anuncio = apps.get_model('anuncios', 'Anuncio')
    for anc in Anuncio.objects.all():
        if anc.status_sincronizacao == 'ENVIADO':
            anc.status_sincronizacao = 'SINCRONIZADO'
        elif anc.status_sincronizacao == 'CANCELADO':
            anc.status_sincronizacao = 'IGNORADO'
        elif anc.status_sincronizacao == 'PENDENTE':
            anc.status_sincronizacao = 'PENDENTE'
        anc.save(update_fields=['status_sincronizacao'])


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0003_anuncio_status_sincronizacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='status_sincronizacao',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('ENVIADO', 'Enviado'), ('CANCELADO', 'Cancelado')], db_index=True, default='PENDENTE', max_length=20, verbose_name='Estado da Sincronização'),
        ),
        migrations.CreateModel(
            name='HistoricoSincronizacaoAnuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_resultante', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ENVIADO', 'Enviado'), ('CANCELADO', 'Cancelado')], max_length=20, verbose_name='Status Resultante')),
                ('preco_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Anterior (R$)')),
                ('preco_proposto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Proposto / Atualizado (R$)')),
                ('estoque_anterior', models.IntegerField(blank=True, null=True, verbose_name='Estoque / Cota Anterior')),
                ('estoque_proposto', models.IntegerField(blank=True, null=True, verbose_name='Estoque / Cota Proposta')),
                ('motivo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Motivo / Operação')),
                ('data_pendencia', models.DateTimeField(blank=True, null=True, verbose_name='Data / Hora da Pendência')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data / Hora da Decisão / Registro')),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_ciclo', to='anuncios.anuncio', verbose_name='Anúncio')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Histórico de Ciclo do Anúncio',
                'verbose_name_plural': 'Históricos de Ciclos dos Anúncios',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.RunPython(migrar_status_sincronizacao, reverter_migracao_status),
    ]
