# Generated by Django 6.1 on 2026-09-10 11:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0004_alter_anuncio_status_sincronizacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicosincronizacaoanuncio',
            name='snapshot_antes',
            field=models.JSONField(blank=True, default=dict, verbose_name='Snapshot Antes da Operação'),
        ),
        migrations.AddField(
            model_name='historicosincronizacaoanuncio',
            name='snapshot_depois',
            field=models.JSONField(blank=True, default=dict, verbose_name='Snapshot Depois da Operação'),
        ),
        migrations.AlterField(
            model_name='historicosincronizacaoanuncio',
            name='criado_em',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data / Hora da Decisão / Registro'),
        ),
    ]
