# Generated by Django 6.1 on 2026-10-03 05:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0005_historicosincronizacaoanuncio_snapshot_antes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador único universal para exposição pública e rotas (mitigação de IDOR/BOLA).', null=True, verbose_name='Identificador Público (UUID)'),
        ),
        migrations.AddField(
            model_name='anunciocomposicao',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador único universal para exposição pública e rotas (mitigação de IDOR/BOLA).', null=True, verbose_name='Identificador Público (UUID)'),
        ),
    ]
