# Generated by Django 6.1 on 2026-09-02 04:47

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplaces', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Categoria')),
                ('slug', models.SlugField(max_length=120, verbose_name='Identificador (Slug)')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição da Categoria')),
                ('ativo', models.BooleanField(default=True, verbose_name='Categoria Ativa')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='tenancy.loja', verbose_name='Loja (Tenant)')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
                'unique_together': {('loja', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=60, verbose_name='Código SKU (Identificador Único na Loja)')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Produto')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição Detalhada do Produto')),
                ('preco', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Preço de Venda (R$)')),
                ('estoque', models.IntegerField(default=0, verbose_name='Saldo de Estoque Físico')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo (Disponível para venda)'), ('INATIVO', 'Inativo (Pausado)'), ('RASCUNHO', 'Rascunho (Em elaboração)')], default='ATIVO', max_length=20, verbose_name='Status do Produto')),
                ('custo_aquisicao', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Custo de compra ou fabricação unitária do produto.', max_digits=10, verbose_name='Custo de Aquisição / CMV (R$)')),
                ('custo_embalagem', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Custo de embalagem deste produto. Se 0, herda o padrão da loja.', max_digits=10, verbose_name='Custo Específico de Embalagem (R$)')),
                ('modalidade_full', models.BooleanField(default=False, help_text='Se marcado, o custo próprio de embalagem é zerado pois o marketplace assume o envio.', verbose_name='Modalidade Full / Fulfillment')),
                ('status_sincronizacao', models.CharField(choices=[('NAO_SINCRONIZADO', 'Não Sincronizado'), ('PENDENTE', 'Sincronização Pendente'), ('SINCRONIZADO', 'Sincronizado com Sucesso'), ('ERRO', 'Erro de Sincronização')], default='NAO_SINCRONIZADO', max_length=20, verbose_name='Status de Sincronização Geral')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='catalogo.categoria', verbose_name='Categoria')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='tenancy.loja', verbose_name='Loja (Tenant)')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome'],
                'unique_together': {('loja', 'sku')},
            },
        ),
        migrations.CreateModel(
            name='HistoricoPreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_anterior', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Anterior (R$)')),
                ('preco_novo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Novo Preço (R$)')),
                ('motivo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Motivo da Alteração')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data / Hora da Alteração')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_precos', to='tenancy.loja', verbose_name='Loja (Tenant)')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='precos_alterados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_precos', to='catalogo.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Histórico de Preço',
                'verbose_name_plural': 'Históricos de Preços',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='AnuncioMarketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id_externo', models.CharField(db_index=True, max_length=100, verbose_name='ID Externo no Marketplace (MLB... / Shopee ID / Magalu SKU)')),
                ('status_anuncio', models.CharField(default='ativo', max_length=30, verbose_name='Status do Anúncio no Canal')),
                ('preco_sincronizado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Último Preço Sincronizado (R$)')),
                ('link_anuncio', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL Pública do Anúncio')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('conta_marketplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anuncios', to='marketplaces.contamarketplace', verbose_name='Conta do Canal')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anuncios', to='catalogo.produto', verbose_name='Produto no Hub')),
            ],
            options={
                'verbose_name': 'Anúncio no Marketplace',
                'verbose_name_plural': 'Anúncios nos Marketplaces',
                'ordering': ['-criado_em'],
                'unique_together': {('conta_marketplace', 'item_id_externo')},
            },
        ),
    ]
