# Generated by Django 6.1 on 2026-09-02 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
        ('marketplaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='anunciomarketplace',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='anunciomarketplace',
            name='ultima_sincronizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Sincronização'),
        ),
        migrations.AlterField(
            model_name='anunciomarketplace',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anuncios', to='catalogo.produto', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='anunciomarketplace',
            name='status_anuncio',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('pausado', 'Pausado'), ('finalizado', 'Finalizado'), ('pendente', 'Pendente')], default='ativo', max_length=30, verbose_name='Status do Anúncio no Canal'),
        ),
        migrations.AlterUniqueTogether(
            name='anunciomarketplace',
            unique_together={('produto', 'conta_marketplace')},
        ),
    ]
