# Generated by Django 6.1 on 2026-09-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_alter_anunciomarketplace_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicopreco',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Histórico de Alteração de Preço e Estoque', 'verbose_name_plural': 'Históricos de Alterações de Preço e Estoque'},
        ),
        migrations.AddField(
            model_name='historicopreco',
            name='estoque_anterior',
            field=models.IntegerField(blank=True, null=True, verbose_name='Estoque Anterior'),
        ),
        migrations.AddField(
            model_name='historicopreco',
            name='estoque_novo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Novo Estoque'),
        ),
        migrations.AlterField(
            model_name='historicopreco',
            name='motivo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Motivo / Operação'),
        ),
        migrations.AlterField(
            model_name='historicopreco',
            name='preco_anterior',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Anterior (R$)'),
        ),
        migrations.AlterField(
            model_name='historicopreco',
            name='preco_novo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Novo Preço (R$)'),
        ),
    ]
