# Generated by Django 6.1 on 2026-09-02 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaMarketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('mercadolivre', 'Mercado Livre'), ('shopee', 'Shopee'), ('magalu', 'Magazine Luiza'), ('amazon', 'Amazon')], max_length=30, verbose_name='Canal de Marketplace')),
                ('apelido_conta', models.CharField(help_text='Identificador amigável (Ex: Loja Principal ML, Shopee Filial)', max_length=100, verbose_name='Apelido da Conta')),
                ('ativo', models.BooleanField(default=True, verbose_name='Integração Ativa')),
                ('client_id', models.CharField(blank=True, max_length=150, null=True, verbose_name='Client ID / App ID')),
                ('client_secret', models.CharField(blank=True, max_length=255, null=True, verbose_name='Client Secret / Chave Secreta')),
                ('access_token', models.TextField(blank=True, null=True, verbose_name='Access Token')),
                ('refresh_token', models.TextField(blank=True, null=True, verbose_name='Refresh Token')),
                ('token_expira_em', models.DateTimeField(blank=True, null=True, verbose_name='Token Expira Em')),
                ('seller_id_externo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Seller ID Externo / User ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Conectado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas_marketplace', to='tenancy.loja', verbose_name='Loja (Tenant)')),
            ],
            options={
                'verbose_name': 'Conta de Marketplace',
                'verbose_name_plural': 'Contas de Marketplaces',
                'ordering': ['loja', 'canal', 'apelido_conta'],
                'unique_together': {('loja', 'canal', 'seller_id_externo')},
            },
        ),
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(choices=[('CRIACAO_CONTA', 'Cadastro de Conta de Marketplace'), ('EDICAO_CONTA', 'Edição de Conta de Marketplace'), ('EXCLUSAO_CONTA', 'Exclusão de Conta de Marketplace'), ('TESTE_CONEXAO', 'Teste de Conexão com API Externa'), ('REFRESH_TOKEN', 'Renovação de Token OAuth'), ('SYNC_PRECO', 'Sincronização de Preço'), ('SYNC_PRECO_LOTE', 'Sincronização de Preço em Lote'), ('SYNC_ESTOQUE', 'Sincronização de Estoque'), ('BROADCAST_ESTOQUE', 'Broadcast Multi-Canal de Estoque'), ('PUBLICACAO_ANUNCIO', 'Publicação de Anúncio'), ('WEBHOOK_RECEBIDO', 'Webhook de Venda Recebido'), ('BAIXA_ESTOQUE_VENDA', 'Baixa Automática de Estoque por Venda'), ('ALERTA_RUPTURA_ESTOQUE', 'Alerta de Ruptura / Saldo Negativo'), ('CRIACAO_PRODUTO', 'Cadastro de Produto'), ('EDICAO_PRODUTO', 'Edição de Produto'), ('EXCLUSAO_PRODUTO', 'Exclusão de Produto'), ('ALTERACAO_PRECO', 'Alteração Manual de Preço'), ('AJUSTE_ESTOQUE', 'Ajuste Geral de Estoque'), ('BAIXA_AVARIA', 'Baixa de Estoque por Avaria'), ('CRIACAO_CATEGORIA', 'Cadastro de Categoria'), ('EDICAO_CATEGORIA', 'Edição de Categoria'), ('EXCLUSAO_CATEGORIA', 'Exclusão de Categoria')], max_length=50, verbose_name='Evento')),
                ('detalhes', models.TextField(verbose_name='Detalhes da Ação / Histórico de Alterações')),
                ('ip_origem', models.CharField(blank=True, max_length=45, null=True, verbose_name='IP de Origem')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data / Hora do Evento')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Autor da Ação')),
                ('loja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_auditoria', to='tenancy.loja', verbose_name='Loja (Tenant)')),
                ('usuario_afetado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_recebidos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Afetado')),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='LogSincronizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('mercadolivre', 'Mercado Livre'), ('shopee', 'Shopee'), ('magalu', 'Magazine Luiza'), ('amazon', 'Amazon')], default='mercadolivre', max_length=30, verbose_name='Canal de Marketplace')),
                ('evento', models.CharField(choices=[('CRIACAO_CONTA', 'Cadastro de Conta de Marketplace'), ('EDICAO_CONTA', 'Edição de Conta de Marketplace'), ('EXCLUSAO_CONTA', 'Exclusão de Conta de Marketplace'), ('TESTE_CONEXAO', 'Teste de Conexão com API Externa'), ('REFRESH_TOKEN', 'Renovação de Token OAuth'), ('SYNC_PRECO', 'Sincronização de Preço'), ('SYNC_PRECO_LOTE', 'Sincronização de Preço em Lote'), ('SYNC_ESTOQUE', 'Sincronização de Estoque'), ('BROADCAST_ESTOQUE', 'Broadcast Multi-Canal de Estoque'), ('PUBLICACAO_ANUNCIO', 'Publicação de Anúncio'), ('WEBHOOK_RECEBIDO', 'Webhook de Venda Recebido'), ('BAIXA_ESTOQUE_VENDA', 'Baixa Automática de Estoque por Venda'), ('ALERTA_RUPTURA_ESTOQUE', 'Alerta de Ruptura / Saldo Negativo'), ('CRIACAO_PRODUTO', 'Cadastro de Produto'), ('EDICAO_PRODUTO', 'Edição de Produto'), ('EXCLUSAO_PRODUTO', 'Exclusão de Produto'), ('ALTERACAO_PRECO', 'Alteração Manual de Preço'), ('AJUSTE_ESTOQUE', 'Ajuste Geral de Estoque'), ('BAIXA_AVARIA', 'Baixa de Estoque por Avaria'), ('CRIACAO_CATEGORIA', 'Cadastro de Categoria'), ('EDICAO_CATEGORIA', 'Edição de Categoria'), ('EXCLUSAO_CATEGORIA', 'Exclusão de Categoria')], max_length=50, verbose_name='Tipo de Operação / Evento')),
                ('item_id_externo', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Externo no Marketplace')),
                ('payload_enviado', models.JSONField(blank=True, default=dict, verbose_name='Payload Enviado (JSON)')),
                ('resposta_recebida', models.JSONField(blank=True, default=dict, verbose_name='Resposta Recebida da API (JSON)')),
                ('status_http', models.IntegerField(blank=True, null=True, verbose_name='Status HTTP')),
                ('sucesso', models.BooleanField(default=False, verbose_name='Operação Bem-Sucedida')),
                ('mensagem_erro', models.TextField(blank=True, null=True, verbose_name='Mensagem de Erro / Diagnóstico')),
                ('tempo_resposta_ms', models.IntegerField(blank=True, null=True, verbose_name='Tempo de Resposta (ms)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data / Hora do Disparo')),
                ('conta_marketplace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='marketplaces.contamarketplace', verbose_name='Conta de Origem')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_sincronizacao', to='tenancy.loja', verbose_name='Loja (Tenant)')),
            ],
            options={
                'verbose_name': 'Log de Sincronização',
                'verbose_name_plural': 'Logs de Sincronização',
                'ordering': ['-criado_em'],
            },
        ),
    ]
