# Generated by Django 6.1 on 2026-09-04 04:42

import apps.marketplaces.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaces', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contamarketplace',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='contamarketplace',
            name='client_secret',
        ),
        migrations.AddField(
            model_name='contamarketplace',
            name='ultima_sincronizacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última Sincronização'),
        ),
        migrations.AlterField(
            model_name='contamarketplace',
            name='access_token',
            field=apps.marketplaces.fields.EncryptedTextField(blank=True, null=True, verbose_name='Access Token'),
        ),
        migrations.AlterField(
            model_name='contamarketplace',
            name='refresh_token',
            field=apps.marketplaces.fields.EncryptedTextField(blank=True, null=True, verbose_name='Refresh Token'),
        ),
    ]
