# Generated by Django 6.1 on 2026-09-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaces', '0002_remove_contamarketplace_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contamarketplace',
            name='is_mock',
            field=models.BooleanField(default=False, help_text='Indica se a conta pertence ao conjunto de lojas e dados fictícios de teste.', verbose_name='Conta Simulada / Mock'),
        ),
    ]
