# Generated by Django 6.1 on 2026-09-05 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaces', '0003_contamarketplace_is_mock'),
        ('tenancy', '0002_alter_loja_pais_alter_loja_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contamarketplace',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='contamarketplace',
            constraint=models.UniqueConstraint(fields=('loja', 'canal'), name='unique_conta_loja_canal'),
        ),
        migrations.AddConstraint(
            model_name='contamarketplace',
            constraint=models.UniqueConstraint(fields=('loja', 'apelido_conta'), name='unique_conta_loja_apelido'),
        ),
        migrations.AddConstraint(
            model_name='contamarketplace',
            constraint=models.UniqueConstraint(condition=models.Q(('seller_id_externo__isnull', False), models.Q(('seller_id_externo', ''), _negated=True)), fields=('canal', 'seller_id_externo'), name='unique_conta_canal_seller_id'),
        ),
    ]
