# Generated by Django 6.1 on 2026-09-07 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaces', '0004_alter_contamarketplace_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.CharField(default='mercadolivre', max_length=50, verbose_name='Marketplace de Origem')),
                ('topic', models.CharField(max_length=50, verbose_name='Tópico da Notificação (ex: orders_v2, items)')),
                ('resource', models.CharField(db_index=True, max_length=255, verbose_name='Recurso Notificado (ex: /orders/2000001234567890)')),
                ('user_id', models.CharField(max_length=50, verbose_name='ID do Usuário / Vendedor no Canal')),
                ('payload_raw', models.JSONField(default=dict, verbose_name='Payload Bruto da Notificação')),
                ('status', models.CharField(choices=[('RECEBIDO', 'Recebido'), ('PROCESSANDO', 'Processando'), ('PROCESSADO', 'Processado'), ('IGNORADO', 'Ignorado'), ('ERRO', 'Erro')], db_index=True, default='RECEBIDO', max_length=20, verbose_name='Status de Processamento')),
                ('error_log', models.TextField(blank=True, null=True, verbose_name='Log de Erro / Justificativa')),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Recebido em')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processado em')),
            ],
            options={
                'verbose_name': 'Log de Evento de Webhook',
                'verbose_name_plural': 'Logs de Eventos de Webhooks',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['marketplace', 'resource', 'status'], name='idx_wh_mkt_res_status'), models.Index(fields=['resource', 'status'], name='idx_wh_res_status'), models.Index(fields=['received_at'], name='idx_wh_received_at')],
            },
        ),
    ]
