# Generated by Django 6.1 on 2026-09-13 22:40

import apps.core.security
import uuid
from django.db import migrations, models


def populate_unique_webhook_uuids(apps, schema_editor):
    ContaMarketplace = apps.get_model('marketplaces', 'ContaMarketplace')
    for conta in ContaMarketplace.objects.all():
        conta.webhook_uuid = uuid.uuid4()
        conta.save(update_fields=['webhook_uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaces', '0005_webhookeventlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='contamarketplace',
            name='app_key_or_id',
            field=models.CharField(blank=True, help_text='Identificador público da aplicação: Client ID / Partner ID', max_length=255, null=True, verbose_name='App ID / Partner ID / Client ID'),
        ),
        migrations.AddField(
            model_name='contamarketplace',
            name='app_secret',
            field=apps.core.security.EncryptedTextField(blank=True, help_text='Chave secreta da aplicação (criptografada em repouso via Fernet).', null=True, verbose_name='App Secret / Client Secret / Partner Key'),
        ),
        migrations.AddField(
            model_name='contamarketplace',
            name='tipo_aplicacao',
            field=models.CharField(choices=[('GLOBAL', 'Aplicação Global do Hub (Centralizada)'), ('INDIVIDUAL', 'Aplicação Própria do Tenant (Individual)')], default='GLOBAL', help_text='Define se utiliza credenciais compartilhadas do Hub ou chaves próprias do lojista.', max_length=20, verbose_name='Tipo de Aplicação'),
        ),
        migrations.AddField(
            model_name='contamarketplace',
            name='webhook_secret',
            field=apps.core.security.EncryptedTextField(blank=True, help_text='Chave secreta para validação de assinatura HMAC dos webhooks.', null=True, verbose_name='Webhook Secret'),
        ),
        migrations.AddField(
            model_name='contamarketplace',
            name='webhook_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, null=True, verbose_name='UUID do Webhook'),
        ),
        migrations.RunPython(populate_unique_webhook_uuids, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='contamarketplace',
            name='webhook_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID do Webhook'),
        ),
    ]
