# Generated by Django 6.1 on 2026-10-03 05:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaces', '0006_contamarketplace_app_key_or_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contamarketplace',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador único universal para exposição pública e rotas (mitigação de IDOR/BOLA).', null=True, verbose_name='Identificador Público (UUID)'),
        ),
        migrations.AddField(
            model_name='webhookeventlog',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador único universal para exposição pública e rotas (mitigação de IDOR/BOLA).', null=True, verbose_name='Identificador Público (UUID)'),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='evento',
            field=models.CharField(choices=[('CRIACAO_CONTA', 'Cadastro de Conta de Marketplace'), ('EDICAO_CONTA', 'Edição de Conta de Marketplace'), ('EXCLUSAO_CONTA', 'Exclusão de Conta de Marketplace'), ('TESTE_CONEXAO', 'Teste de Conexão com API Externa'), ('REFRESH_TOKEN', 'Renovação de Token OAuth'), ('SYNC_PRECO', 'Sincronização de Preço'), ('SYNC_PRECO_LOTE', 'Sincronização de Preço em Lote'), ('SYNC_ESTOQUE', 'Sincronização de Estoque'), ('BROADCAST_ESTOQUE', 'Broadcast Multi-Canal de Estoque'), ('PUBLICACAO_ANUNCIO', 'Publicação de Anúncio'), ('WEBHOOK_RECEBIDO', 'Webhook de Venda Recebido'), ('BAIXA_ESTOQUE_VENDA', 'Baixa Automática de Estoque por Venda'), ('ALERTA_RUPTURA_ESTOQUE', 'Alerta de Ruptura / Saldo Negativo'), ('CRIACAO_PRODUTO', 'Cadastro de Produto'), ('EDICAO_PRODUTO', 'Edição de Produto'), ('EXCLUSAO_PRODUTO', 'Exclusão de Produto'), ('ALTERACAO_PRECO', 'Alteração Manual de Preço'), ('AJUSTE_ESTOQUE', 'Ajuste Geral de Estoque'), ('BAIXA_AVARIA', 'Baixa de Estoque por Avaria'), ('CRIACAO_CATEGORIA', 'Cadastro de Categoria'), ('EDICAO_CATEGORIA', 'Edição de Categoria'), ('EXCLUSAO_CATEGORIA', 'Exclusão de Categoria'), ('ALTERACAO_MATRIZ_RBAC', 'Alteração da Matriz RBAC')], max_length=50, verbose_name='Evento'),
        ),
        migrations.AlterField(
            model_name='logsincronizacao',
            name='evento',
            field=models.CharField(choices=[('CRIACAO_CONTA', 'Cadastro de Conta de Marketplace'), ('EDICAO_CONTA', 'Edição de Conta de Marketplace'), ('EXCLUSAO_CONTA', 'Exclusão de Conta de Marketplace'), ('TESTE_CONEXAO', 'Teste de Conexão com API Externa'), ('REFRESH_TOKEN', 'Renovação de Token OAuth'), ('SYNC_PRECO', 'Sincronização de Preço'), ('SYNC_PRECO_LOTE', 'Sincronização de Preço em Lote'), ('SYNC_ESTOQUE', 'Sincronização de Estoque'), ('BROADCAST_ESTOQUE', 'Broadcast Multi-Canal de Estoque'), ('PUBLICACAO_ANUNCIO', 'Publicação de Anúncio'), ('WEBHOOK_RECEBIDO', 'Webhook de Venda Recebido'), ('BAIXA_ESTOQUE_VENDA', 'Baixa Automática de Estoque por Venda'), ('ALERTA_RUPTURA_ESTOQUE', 'Alerta de Ruptura / Saldo Negativo'), ('CRIACAO_PRODUTO', 'Cadastro de Produto'), ('EDICAO_PRODUTO', 'Edição de Produto'), ('EXCLUSAO_PRODUTO', 'Exclusão de Produto'), ('ALTERACAO_PRECO', 'Alteração Manual de Preço'), ('AJUSTE_ESTOQUE', 'Ajuste Geral de Estoque'), ('BAIXA_AVARIA', 'Baixa de Estoque por Avaria'), ('CRIACAO_CATEGORIA', 'Cadastro de Categoria'), ('EDICAO_CATEGORIA', 'Edição de Categoria'), ('EXCLUSAO_CATEGORIA', 'Exclusão de Categoria'), ('ALTERACAO_MATRIZ_RBAC', 'Alteração da Matriz RBAC')], max_length=50, verbose_name='Tipo de Operação / Evento'),
        ),
    ]
