# Generated by Django 6.1 on 2026-10-04 04:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaces', '0008_alter_contamarketplace_public_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logauditoria',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador único universal para exposição pública e rotas (mitigação de IDOR/BOLA).', null=True, verbose_name='Identificador Público (UUID)'),
        ),
    ]
