# Generated by Django 6.1 on 2026-10-04 04:11

import uuid
from django.db import migrations, models


def popular_uuids(apps, schema_editor):
    LogAuditoria = apps.get_model('marketplaces', 'LogAuditoria')
    for row in LogAuditoria.objects.all():
        row.public_id = uuid.uuid4()
        row.save(update_fields=['public_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaces', '0009_logauditoria_public_id'),
    ]

    operations = [
        migrations.RunPython(popular_uuids, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='logauditoria',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador único universal para exposição pública e rotas (mitigação de IDOR/BOLA).', unique=True, verbose_name='Identificador Público (UUID)'),
        ),
    ]
