# Os códigos foram gerados com auxilio de I.A.
"""
Django settings for hub project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""
import os
import sys
import environ
from pathlib import Path

# Define a raiz do projeto (onde está o arquivo .env)
BASE_DIR = Path(__file__).resolve().parent.parent

# Adiciona o diretório apps ao sys.path para resolução transparente de módulos
APPS_DIR = BASE_DIR / 'apps'
if str(APPS_DIR) not in sys.path:
    sys.path.insert(0, str(APPS_DIR))

# Inicializa o leitor de variáveis de ambiente com tipo booleano padrão para o DEBUG
env = environ.Env(
    DEBUG=(bool, False)
)

# Faz a leitura do arquivo .env localizado na raiz do projeto
environ.Env.read_env(BASE_DIR / '.env')

# Substitua as linhas originais do Django por estas que lêem o arquivo oculto de forma tipada:
SECRET_KEY = env('SECRET_KEY')
# Lê DEBUG do .env (se não encontrar, assume False por segurança)
DEBUG = env.bool('DEBUG', default=False)
# Lê LOGIN_DEBUG do .env para injeção automática de credenciais em desenvolvimento
LOGIN_DEBUG = env.bool('LOGIN_DEBUG', default=False)
LOGIN_DEBUG_USERNAME = env.str('LOGIN_DEBUG_USERNAME', default='devmaster')
LOGIN_DEBUG_PASSWORD = env.str('LOGIN_DEBUG_PASSWORD', default='')
LOGIN_DEBUG_EMAIL = env.str('LOGIN_DEBUG_EMAIL', default='devmaster@hub.local')

# Lê ALLOWED_HOSTS como lista separada por vírgulas do .env (ex: 127.0.0.1,localhost)
ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['127.0.0.1', 'localhost', 'testserver', 'material-playing-outshoot.ngrok-free.dev', '.ngrok-free.dev'])
CSRF_TRUSTED_ORIGINS = ['https://material-playing-outshoot.ngrok-free.dev']

# Permite que o Django reconheça HTTPS vindo do Ngrok / Reverse Proxy
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Novos Apps Modulares Desacoplados
    'apps.tenancy.apps.TenancyConfig',
    'apps.marketplaces.apps.MarketplacesConfig',
    'apps.catalogo.apps.CatalogoConfig',
    'apps.anuncios.apps.AnunciosConfig',
    'apps.pedidos.apps.PedidosConfig',
    'apps.financeiro.apps.FinanceiroConfig',

    # Módulo Dedicado de Mock de Dados (Ambiente de Testes / Debug)
    'apps.mockar_dados.apps.MockarDadosConfig',
    
    # bibliotecas de terceiros
    'django_extensions',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'hub.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.tenancy.context_processors.modulos_loja_context',
                'apps.mockar_dados.context_processors.login_debug_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'hub.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Autenticação e Redirecionamentos
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'login'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

# ==============================================================================
# MERCADO LIVRE - OAUTH 2.0 & CRIPTOGRAFIA DE DADOS EM REPOUSO
# ==============================================================================
MERCADOLIVRE_CORE_CLIENT_ID = os.getenv("MERCADOLIVRE_CORE_CLIENT_ID", "")
MERCADOLIVRE_CORE_CLIENT_SECRET = os.getenv("MERCADOLIVRE_CORE_CLIENT_SECRET", "")
MERCADOLIVRE_CLIENT_ID = os.getenv("MERCADOLIVRE_CLIENT_ID", MERCADOLIVRE_CORE_CLIENT_ID)
MERCADOLIVRE_CLIENT_SECRET = os.getenv("MERCADOLIVRE_CLIENT_SECRET", MERCADOLIVRE_CORE_CLIENT_SECRET)
MERCADOLIVRE_REDIRECT_URI = os.getenv(
    "MERCADOLIVRE_REDIRECT_URI",
    "https://oauth.pstmn.io/v1/callback"
)
FIELD_ENCRYPTION_KEY = os.getenv("FIELD_ENCRYPTION_KEY", "")

# ==============================================================================
# FEATURE FLAG: SIMULAÇÃO DE ROTAS MOCK (OAUTH & APIS DE MARKETPLACES)
# ==============================================================================
SIMULAR_ROTAS_MOCK = os.getenv("SIMULAR_ROTAS_MOCK", "True").lower() in ("true", "1", "yes")

