# Os códigos foram gerados com auxilio de I.A.

# Início do bloco de docstring que documenta o arquivo e links para a documentação oficial do Django
"""
Django settings for hub project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""
# Fim do bloco de docstring de metadados do projeto

# Importa o módulo 'os' da biblioteca padrão para interações com variáveis de ambiente e o sistema operacional
import os

# Importa o módulo 'sys' para permitir manipulação da lista de caminhos de busca de módulos do interpretador Python
import sys

# Importa a biblioteca de terceiros 'environ' (django-environ) para realizar a leitura tipada de variáveis do arquivo .env
import environ

# Importa a classe orientada a objetos 'Path' do módulo 'pathlib' para manipulação segura de caminhos de arquivos e pastas
from pathlib import Path

# Define a raiz do projeto (onde está o arquivo .env)
# Resolve o caminho absoluto do diretório-pai da pasta atual (hub), apontando para a raiz do repositório
BASE_DIR = Path(__file__).resolve().parent.parent

# Adiciona o diretório apps ao sys.path para resolução transparente de módulos
# Constrói o caminho completo até o diretório interno 'apps' a partir da raiz do projeto
APPS_DIR = BASE_DIR / 'apps'

# Verifica se o caminho do diretório 'apps' já não está registrado na lista de busca do Python
if str(APPS_DIR) not in sys.path:
    # Insere o caminho de 'apps' na primeira posição do sys.path para permitir importações diretas dos sub-aplicativos
    sys.path.insert(0, str(APPS_DIR))

# Inicializa o leitor de variáveis de ambiente com tipo booleano padrão para o DEBUG
# Cria a instância de leitura definindo o valor padrão de DEBUG como booleano False por precaução de segurança
env = environ.Env(
    DEBUG=(bool, False)
)

# Faz a leitura do arquivo .env localizado na raiz do projeto
# Lê o arquivo físico '.env' na raiz e carrega as variáveis na memória do processo
environ.Env.read_env(BASE_DIR / '.env')

# Substitua as linhas originais do Django por estas que lêem o arquivo oculto de forma tipada:
# Extrai o valor obrigatório de SECRET_KEY do .env, usado para assinatura de sessões e tokens criptográficos
SECRET_KEY = env('SECRET_KEY')

# Lê DEBUG do .env (se não encontrar, assume False por segurança)
# Converte a variável DEBUG para tipo booleano nativo, mantendo False como fallback seguro
DEBUG = env.bool('DEBUG', default=False)

# Lê LOGIN_DEBUG do .env para injeção automática de credenciais em desenvolvimento
# Carrega a flag que habilita o preenchimento ou login automático rápido em ambientes de desenvolvimento
LOGIN_DEBUG = env.bool('LOGIN_DEBUG', default=False)

# Obtém a string com o nome de usuário padrão usado para autenticação no modo de desenvolvimento
LOGIN_DEBUG_USERNAME = env.str('LOGIN_DEBUG_USERNAME', default='devmaster')

# Obtém a string com a senha correspondente ao usuário de teste rápido em desenvolvimento
LOGIN_DEBUG_PASSWORD = env.str('LOGIN_DEBUG_PASSWORD', default='')

# Obtém a string com o endereço de e-mail atrelado a esse usuário de testes local
LOGIN_DEBUG_EMAIL = env.str('LOGIN_DEBUG_EMAIL', default='devmaster@hub.local')

# Lê ALLOWED_HOSTS como lista separada por vírgulas do .env (ex: 127.0.0.1,localhost)
# Define quais domínios e IPs têm autorização para se comunicar com esta instância Django, incluindo túneis ngrok
ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['127.0.0.1', 'localhost', 'testserver', 'material-playing-outshoot.ngrok-free.dev', '.ngrok-free.dev'])

# Lista de URLs de origens seguras confiáveis para validação dos cabeçalhos CSRF em requisições POST externas
CSRF_TRUSTED_ORIGINS = ['https://material-playing-outshoot.ngrok-free.dev']

# Permite que o Django reconheça HTTPS vindo do Ngrok / Reverse Proxy
# Instrução para inspecionar o cabeçalho 'HTTP_X_FORWARDED_PROTO' e confirmar se o cliente acessou via protocolo HTTPS
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Determina que o Django utilize o cabeçalho 'X-Forwarded-Host' como host original da requisição HTTP
USE_X_FORWARDED_HOST = True

# Determina que o Django utilize o cabeçalho 'X-Forwarded-Port' para identificar a porta original da requisição HTTP
USE_X_FORWARDED_PORT = True

# Application definition
# Comentário de seção padrão para o registro dos pacotes de funcionalidades instalados no Django

# Lista que centraliza todos os módulos, aplicativos nativos e extensões ativas no projeto
INSTALLED_APPS = [
    # Módulo nativo do Django para interface gráfica de administração de modelos
    'django.contrib.admin',
    # Framework nativo de autenticação, usuários e grupos de permissões
    'django.contrib.auth',
    # Sistema nativo de mapeamento de tipos de conteúdo e permissões genéricas
    'django.contrib.contenttypes',
    # Gerenciador nativo de sessões de usuário baseadas em cookies/banco
    'django.contrib.sessions',
    # Framework nativo para disparo e exibição de mensagens e alertas temporários
    'django.contrib.messages',
    # Utilitário para coleta e publicação de arquivos estáticos (CSS, JavaScript, imagens)
    'django.contrib.staticfiles',
    
    # Novos Apps Modulares Desacoplados
    # Registra o app core com classes utilitárias, mixins e modelos transversais da plataforma
    'apps.core.apps.CoreConfig',
    # Registra o app tenancy responsável pelo isolamento multi-inquilino e contexto de lojas
    'apps.tenancy.apps.TenancyConfig',
    # Registra o conector responsável pelas integrações e comunicações com canais de venda externos
    'apps.marketplaces.apps.MarketplacesConfig',
    # Registra o domínio de catálogo de produtos, categorias, variações e controle de estoque
    'apps.catalogo.apps.CatalogoConfig',
    # Registra o domínio de publicação de anúncios, regras de precificação e vínculos com marketplaces
    'apps.anuncios.apps.AnunciosConfig',
    # Registra o domínio de pedidos, esteira de faturamento, despacho e ciclo de vida de compras
    'apps.pedidos.apps.PedidosConfig',
    # Registra o módulo de gestão financeira, comissões dos canais, tarifas e conciliações
    'apps.financeiro.apps.FinanceiroConfig',

    # Módulo Dedicado de Mock de Dados (Ambiente de Testes / Debug)
    # App isolado contendo geradores de dados sintéticos e rotas falsas para testes sem chamadas reais
    'apps.mockar_dados.apps.MockarDadosConfig',
    
    # bibliotecas de terceiros
    # Registra conjunto de ferramentas extras para desenvolvimento (shell estendido, comandos adicionais)
    'django_extensions',
]

# Lista sequencial de middlewares que interceptam e processam cada requisição e resposta HTTP
MIDDLEWARE = [
    # Camada que aplica cabeçalhos de proteção como HSTS e proteção contra spoofing
    'django.middleware.security.SecurityMiddleware',
    # Camada que recupera ou instancia o objeto de sessão vinculado ao cookie da requisição
    'django.contrib.sessions.middleware.SessionMiddleware',
    # Camada que aplica regras genéricas de URL, compressão e validações básicas de cabeçalho
    'django.middleware.common.CommonMiddleware',
    # Camada de segurança contra ataques de falsificação de solicitação entre sites (CSRF)
    'django.middleware.csrf.CsrfViewMiddleware',
    # Camada que associa a instância de usuário logado ao objeto da requisição (request.user)
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # Camada que carrega mensagens de notificação salvas na sessão para a requisição atual
    'django.contrib.messages.middleware.MessageMiddleware',
    # Camada que insere cabeçalhos X-Frame-Options para impedir exibição indevida da página em iframes
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Especifica o módulo Python que contém a definição das rotas raiz de URLs da aplicação
ROOT_URLCONF = 'hub.urls'

# Configuração da engine de renderização dos modelos de telas HTML (templates)
TEMPLATES = [
    {
        # Define a utilização da engine nativa de templates do Django
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Especifica o diretório raiz customizado 'templates' onde arquivos HTML compartilhados serão encontrados
        'DIRS': [BASE_DIR / 'templates'],
        # Instrução para buscar automaticamente subpastas 'templates' dentro de cada app instalado
        'APP_DIRS': True,
        # Opções complementares de contexto passadas para os renderizadores
        'OPTIONS': {
            # Lista de context processors que injetam variáveis globais em qualquer template renderizado
            'context_processors': [
                # Permite referenciar o próprio objeto request dentro das tags do template
                'django.template.context_processors.request',
                # Injeta as permissões e o usuário logado nas variáveis auth e user no HTML
                'django.contrib.auth.context_processors.auth',
                # Torna a coleção de mensagens flash disponível para renderização nas páginas
                'django.contrib.messages.context_processors.messages',
                # Injeta dados e módulos habilitados da loja/inquilino atual no contexto do HTML
                'apps.tenancy.context_processors.modulos_loja_context',
                # Injeta atalhos e credenciais rápidas de depuração no rodapé/painel de templates
                'apps.mockar_dados.context_processors.login_debug_context',
            ],
        },
    },
]

# Aponta para o callable do servidor WSGI padrão para processamento síncrono em produção
WSGI_APPLICATION = 'hub.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases
# Comentário de seção com link para documentação oficial de bancos de dados suportados pelo Django

# Estrutura de conexão aos bancos de dados da aplicação
DATABASES = {
    # Define a base relacional default do sistema
    'default': {
        # Configura o driver de banco nativo para o SQLite
        'ENGINE': 'django.db.backends.sqlite3',
        # Define o local do arquivo SQLite db.sqlite3 armazenado na raiz do projeto
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators
# Comentário de seção referenciando as validações de integridade de senha de usuários

# Validadores executados ao cadastrar ou alterar senhas de acesso
AUTH_PASSWORD_VALIDATORS = [
    {
        # Valida e bloqueia senhas muito parecidas com atributos do perfil (como username ou e-mail)
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        # Valida e exige que a senha tenha uma extensão mínima aceitável de caracteres
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        # Valida e rejeita senhas populares ou óbvias presentes em dicionários conhecidos
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        # Valida e proíbe senhas formadas inteiramente apenas por números
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/
# Comentário com links para opções de fuso horário e idiomas suportados

# Configura a localização padrão do sistema para Português do Brasil
LANGUAGE_CODE = 'pt-br'

# Configura o fuso horário operacional para o Horário Padrão de Brasília
TIME_ZONE = 'America/Sao_Paulo'

# Ativa o sistema interno de tradução e localização de strings do Django
USE_I18N = True

# Instrução para salvar registros de timestamp com dados completos de fuso horário (Timezone-Aware)
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/
# Comentário de referência para o gerenciamento de arquivos estáticos

# Define o prefixo de rota pública HTTP por onde os assets estáticos são requisitados
STATIC_URL = 'static/'


# Autenticação e Redirecionamentos
# Define a rota de destino padrão caso uma página exija autenticação e o usuário seja anônimo
LOGIN_URL = 'login'

# Define para qual rota o usuário autenticado deve ser direcionado após realizar login
LOGIN_REDIRECT_URL = 'home'

# Define para qual rota o usuário deve retornar após encerrar a sessão (logout)
LOGOUT_REDIRECT_URL = 'login'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration
# Comentário de seção para configuração de despacho e transporte de correio eletrônico

# Mapeia as configurações de saída de e-mails do sistema
MAILERS = {
    # Configura o backend padrão de e-mails
    'default': {
        # Redireciona a impressão dos e-mails diretamente para a saída de texto do terminal/console
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

# ==============================================================================
# MERCADO LIVRE - OAUTH 2.0 & CRIPTOGRAFIA DE DADOS EM REPOUSO
# ==============================================================================
# Divisor de seção para credenciais e chaves do canal de integração do Mercado Livre

# Carrega o Client ID da aplicação principal cadastrada no painel Mercado Livre Developers
MERCADOLIVRE_CORE_CLIENT_ID = os.getenv("MERCADOLIVRE_CORE_CLIENT_ID", "")

# Carrega a chave secreta (Client Secret) correspondente à aplicação principal do Mercado Livre
MERCADOLIVRE_CORE_CLIENT_SECRET = os.getenv("MERCADOLIVRE_CORE_CLIENT_SECRET", "")

# Define o Client ID operacional utilizando a variável principal ou assumindo a credencial core como fallback
MERCADOLIVRE_CLIENT_ID = os.getenv("MERCADOLIVRE_CLIENT_ID", MERCADOLIVRE_CORE_CLIENT_ID)

# Define o Client Secret operacional utilizando a variável principal ou a credencial core como fallback
MERCADOLIVRE_CLIENT_SECRET = os.getenv("MERCADOLIVRE_CLIENT_SECRET", MERCADOLIVRE_CORE_CLIENT_SECRET)

# Lê a URL de retorno para recepção do authorization code após o consentimento do lojista no Mercado Livre
MERCADOLIVRE_REDIRECT_URI = os.getenv(
    "MERCADOLIVRE_REDIRECT_URI",
    "https://oauth.pstmn.io/v1/callback"
)

# Chave criptográfica usada para cifrar tokens de acesso e dados sensíveis antes de salvar no banco de dados
FIELD_ENCRYPTION_KEY = os.getenv("FIELD_ENCRYPTION_KEY", "")

# ==============================================================================
# FEATURE FLAG: SIMULAÇÃO DE ROTAS MOCK (OAUTH & APIS DE MARKETPLACES)
# ==============================================================================
# Divisor de seção para chaveamento do ambiente de mock contra APIs externas

# Converte o valor da variável de ambiente para booleano, definindo se as requisições chamarão mocks ou APIs reais
SIMULAR_ROTAS_MOCK = os.getenv("SIMULAR_ROTAS_MOCK", "True").lower() in ("true", "1", "yes")

